name: Build
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: gradle/gradle-build-action@v2
      - run: "./gradlew build"