name: Release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 16
          plugins: [
            "@semantic-release/commit-analyzer",
            "@semantic-release/github",
            "@semantic-release/release-notes-generator",
            "@semantic-release/changelog@3.0.0",
            "@semantic-release/git"
          ]
      - name: After publishing
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
